import prisma from "@/lib/prisma";

export const SELLER_AUDIT_ACTIONS = {
  SELLER_APPLIED: "SELLER_APPLIED",
  SELLER_APPROVED: "SELLER_APPROVED",
  SELLER_REJECTED: "SELLER_REJECTED",
  SELLER_SUSPENDED: "SELLER_SUSPENDED",
  SELLER_ACTIVATED: "SELLER_ACTIVATED",
  SELLER_BLOCKED: "SELLER_BLOCKED",
  SELLER_UNBLOCKED: "SELLER_UNBLOCKED",
  SELLER_NOTES_UPDATED: "SELLER_NOTES_UPDATED",
  COMMISSION_CHANGED: "COMMISSION_CHANGED",
  SELLER_PRODUCT_CREATED: "SELLER_PRODUCT_CREATED",
  SELLER_PRODUCT_UPDATED: "SELLER_PRODUCT_UPDATED",
  SELLER_PRODUCT_DELETED: "SELLER_PRODUCT_DELETED",
  PRODUCT_SUBMITTED: "PRODUCT_SUBMITTED",
  PRODUCT_APPROVED: "PRODUCT_APPROVED",
  PRODUCT_REJECTED: "PRODUCT_REJECTED",
  PAYOUT_REQUESTED: "PAYOUT_REQUESTED",
  PAYOUT_APPROVED: "PAYOUT_APPROVED",
  PAYOUT_PAID: "PAYOUT_PAID",
  PAYOUT_REJECTED: "PAYOUT_REJECTED",
  SELLER_VERIFICATION_SUBMITTED: "SELLER_VERIFICATION_SUBMITTED",
  SELLER_VERIFICATION_RESUBMITTED: "SELLER_VERIFICATION_RESUBMITTED",
  CNIC_VERIFIED: "CNIC_VERIFIED",
  CNIC_REJECTED: "CNIC_REJECTED",
  CNIC_RESUBMISSION_REQUESTED: "CNIC_RESUBMISSION_REQUESTED",
  VERIFICATION_IMAGES_VERIFIED: "VERIFICATION_IMAGES_VERIFIED",
  VERIFICATION_IMAGES_REJECTED: "VERIFICATION_IMAGES_REJECTED",
  VERIFICATION_IMAGES_RESUBMISSION_REQUESTED: "VERIFICATION_IMAGES_RESUBMISSION_REQUESTED",
  LIVE_VIDEO_VERIFIED: "LIVE_VIDEO_VERIFIED",
  LIVE_VIDEO_REJECTED: "LIVE_VIDEO_REJECTED",
  LIVE_VIDEO_RESUBMISSION_REQUESTED: "LIVE_VIDEO_RESUBMISSION_REQUESTED",
  SELLER_IMPORT_STARTED: "SELLER_IMPORT_STARTED",
  SELLER_IMPORT_COMPLETED: "SELLER_IMPORT_COMPLETED",
  SELLER_IMPORT_FAILED: "SELLER_IMPORT_FAILED",
  SELLER_EXPORT_CREATED: "SELLER_EXPORT_CREATED",
  SELLER_PRODUCT_BULK_CREATED: "SELLER_PRODUCT_BULK_CREATED",
} as const;

export type SellerAuditAction = (typeof SELLER_AUDIT_ACTIONS)[keyof typeof SELLER_AUDIT_ACTIONS];

export async function logSellerAudit(input: {
  sellerId: string;
  action: SellerAuditAction | string;
  performedBy?: string;
  target?: string;
  details?: string | Record<string, unknown> | null;
}): Promise<void> {
  try {
    const details =
      typeof input.details === "string" || input.details == null
        ? input.details
        : JSON.stringify(input.details);
    await prisma.sellerAuditLog.create({
      data: {
        sellerId: input.sellerId,
        action: input.action,
        performedBy: input.performedBy || "admin",
        target: input.target || null,
        details: details || null,
      },
    });
  } catch (error) {
    console.error("[SELLER_AUDIT]", error);
  }
}
