import { createHmac, timingSafeEqual } from "crypto";
import {
  PaymentProvider,
  PaymentSession,
  CreateSessionInput,
  PaymentVerificationResult,
  ProviderPaymentStatus,
} from "./types";

/**
 * ──────────────────────────────────────────────────────────────────────────────
 * Easypaisa Payment Hub — Hosted Checkout Integration (Sandbox / Production)
 * ──────────────────────────────────────────────────────────────────────────────
 *
 * ENV VARS REQUIRED (set in .env.local):
 *   NEXT_PUBLIC_EASYPAISA_STORE_ID   — Merchant / Store ID from Easypaisa
 *   EASYPAISA_HASH_KEY               — HMAC-SHA256 secret key from Easypaisa
 *   EASYPAISA_RETURN_URL             — Absolute URL where Easypaisa redirects
 *                                      the customer after payment completion
 *
 * SANDBOX ENDPOINT:
 *   POST https://sandbox.easypaisa.com.pk/ep-integration/merchants/api/v1/send
 *
 * PRODUCTION ENDPOINT:
 *   POST https://easypay.easypaisa.com.pk/ep-integration/merchants/api/v1/send
 *
 * ── HASH SIGNATURE (REQUEST) ──────────────────────────────────────────────────
 *
 * The request signature is an HMAC-SHA256 computed over three pipe-separated
 * fields using the merchant hash key as the HMAC secret:
 *
 *   signature = HMAC-SHA256(
 *     hashKey,
 *     StoreId + OrderId + TransactionAmount
 *   )
 *
 * Where:
 *   - StoreId          = the merchant store identifier (NEXT_PUBLIC_EASYPAISA_STORE_ID)
 *   - OrderId          = unique order reference generated by the merchant
 *   - TransactionAmount = payment amount as a string with 2 decimal places (e.g. "1000.00")
 *
 * The hex-encoded digest is sent in the `signature` field of the JSON body.
 *
 * ── IPN CALLBACK VERIFICATION ─────────────────────────────────────────────────
 *
 * When Easypaisa sends an IPN (Instant Payment Notification), it POSTs form-
 * encoded parameters to your callback URL. To verify authenticity:
 *
 *   expected = HMAC-SHA256(
 *     hashKey,
 *     StoreId + OrderId + TransactionAmount + ResponseCode
 *   )
 *
 * Compare `expected` against the `signature` field in the IPN payload using
 * constant-time comparison to prevent timing attacks.
 *
 * ResponseCode "0000" = success, anything else = failure/pending.
 * ──────────────────────────────────────────────────────────────────────────────
 */

const clean = (v?: string) =>
  (v || "").trim().replace(/^(['"])(.*)\1$/, "$2").trim();

// Sandbox: https://sandbox.easypaisa.com.pk
// Production: https://easypay.easypaisa.com.pk
const EASYPAISA_API_HOST =
  clean(process.env.EASYPAISA_HOST) ||
  "https://sandbox.easypaisa.com.pk";

const EASYPAISA_API_PATH =
  "/ep-integration/merchants/api/v1/send";

/* ────────────────────────────────────────────────────────────────────────────
 * Configuration checks
 * ──────────────────────────────────────────────────────────────────────────── */

export function easypaisaConfigured(): boolean {
  return Boolean(
    clean(process.env.NEXT_PUBLIC_EASYPAISA_STORE_ID) &&
      clean(process.env.EASYPAISA_HASH_KEY)
  );
}

export function easypaisaUnconfiguredReason(): string {
  return (
    "Easypaisa credentials are not configured. " +
    "Set NEXT_PUBLIC_EASYPAISA_STORE_ID and EASYPAISA_HASH_KEY in .env.local."
  );
}

/* ────────────────────────────────────────────────────────────────────────────
 * HMAC-SHA256 hash helper
 *
 * Both request signing and IPN verification use the same algorithm:
 *   HMAC-SHA256(hashKey, concatenatedFields)
 *
 * The hashKey is the merchant secret from Easypaisa. The concatenated
 * fields are specific to each use case (request vs. IPN).
 * ──────────────────────────────────────────────────────────────────────────── */

function computeHmacSha256(secret: string, data: string): string {
  return createHmac("sha256", secret).update(data).digest("hex");
}

/**
 * Build the request signature for initiating a payment.
 *
 * Easypaisa computes:
 *   HMAC-SHA256(hashKey, StoreId + OrderId + TransactionAmount)
 *
 * Note: The fields are concatenated directly (no separator), matching the
 * Easypaisa API specification. The Amount must be a string with 2 decimal
 * places (e.g., "1500.00" for PKR 1,500).
 */
export function buildRequestSignature(
  hashKey: string,
  storeId: string,
  orderId: string,
  amount: string
): string {
  return computeHmacSha256(hashKey, `${storeId}${orderId}${amount}`);
}

/**
 * Verify an IPN (callback) signature from Easypaisa.
 *
 * Easypaisa sends these form-encoded fields on callback:
 *   - StoreId, OrderId, TransactionAmount, ResponseCode, signature, ...
 *
 * The expected signature is:
 *   HMAC-SHA256(hashKey, StoreId + OrderId + TransactionAmount + ResponseCode)
 *
 * We use constant-time comparison (timingSafeEqual) to prevent timing attacks.
 */
export function verifyIpnSignature(
  hashKey: string,
  ipnParams: Record<string, string>
): boolean {
  const storeId = clean(ipnParams.StoreId);
  const orderId = clean(ipnParams.OrderId);
  const amount = clean(ipnParams.TransactionAmount);
  const responseCode = clean(ipnParams.ResponseCode);
  const receivedSig = clean(ipnParams.signature);

  if (!storeId || !orderId || !amount || !responseCode || !receivedSig) {
    return false;
  }

  const expected = computeHmacSha256(
    hashKey,
    `${storeId}${orderId}${amount}${responseCode}`
  );

  // Constant-time comparison to prevent timing side-channel attacks
  const expectedBuf = Buffer.from(expected, "hex");
  const receivedBuf = Buffer.from(receivedSig, "hex");

  if (expectedBuf.length !== receivedBuf.length) return false;
  return timingSafeEqual(expectedBuf, receivedBuf);
}

/**
 * Map Easypaisa ResponseCode to our internal payment status.
 *
 * Easypaisa ResponseCodes:
 *   "0000" — Transaction successful (PAID)
 *   "9999" — Transaction pending / processing (PENDING)
 *   Other  — Transaction failed (FAILED)
 */
function mapResponseCode(
  responseCode: string
): ProviderPaymentStatus {
  if (responseCode === "0000") return "PAID";
  if (responseCode === "9999") return "PENDING";
  return "FAILED";
}

/**
 * Generate a unique merchant order reference.
 *
 * Format: E{timestamp}{random3digits}
 * The "E" prefix identifies this as an Easypaisa transaction.
 */
function generateOrderId(): string {
  return `E${Date.now()}${Math.floor(Math.random() * 1000)}`;
}

/* ────────────────────────────────────────────────────────────────────────────
 * Public IPN verification function (used by webhook route handler)
 * ──────────────────────────────────────────────────────────────────────────── */

export async function verifyEasypaisaCallback(
  params: Record<string, string>
): Promise<{
  valid: boolean;
  status?: ProviderPaymentStatus;
  txn: string | null;
}> {
  if (!easypaisaConfigured()) return { valid: false, txn: null };

  const hashKey = clean(process.env.EASYPAISA_HASH_KEY);
  const txn = clean(params.OrderId) || clean(params.TransactionId) || null;

  if (!txn) return { valid: false, txn: null };

  const valid = verifyIpnSignature(hashKey, params);
  const responseCode = clean(params.ResponseCode);
  const status = valid ? mapResponseCode(responseCode) : undefined;

  return { valid, status, txn };
}

/* ────────────────────────────────────────────────────────────────────────────
 * PaymentProvider implementation
 * ──────────────────────────────────────────────────────────────────────────── */

export const easypaisaProvider: PaymentProvider = {
  id: "easypaisa",

  configured: easypaisaConfigured,

  unconfiguredReason: easypaisaUnconfiguredReason,

  /**
   * Initiate an Easypaisa hosted checkout session.
   *
   * This builds the signed request payload and returns a redirect URL that
   * the checkout page sends the customer to. The actual payment happens on
   * Easypaisa's hosted page — we never handle card/wallet credentials.
   *
   * Flow:
   *  1. Build order reference + amount in paisa format (2 decimal places)
   *  2. Compute HMAC-SHA256 signature = HMAC(hashKey, storeId + orderId + amount)
   *  3. Return redirect URL with signed parameters
   *  4. Customer pays on Easypaisa's hosted page
   *  5. Easypaisa sends IPN to our webhook for server-side verification
   */
  async createSession(input: CreateSessionInput): Promise<PaymentSession> {
    if (!easypaisaConfigured()) {
      throw new Error(easypaisaUnconfiguredReason());
    }

    const storeId = clean(process.env.NEXT_PUBLIC_EASYPAISA_STORE_ID);
    const hashKey = clean(process.env.EASYPAISA_HASH_KEY);
    const returnUrl =
      clean(process.env.EASYPAISA_RETURN_URL) || input.successUrl;

    // Generate a unique order reference for this transaction
    const orderId = generateOrderId();

    // Easypaisa expects amount as a string with exactly 2 decimal places.
    // e.g., PKR 1500 → "1500.00"
    const amount = input.amount.toFixed(2);

    // ── SIGNATURE COMPUTATION ──────────────────────────────────────────
    // signature = HMAC-SHA256(hashKey, StoreId + OrderId + TransactionAmount)
    //
    // The three fields are concatenated with NO separator between them.
    // This is the canonical Easypaisa request signing algorithm.
    const signature = buildRequestSignature(hashKey, storeId, orderId, amount);

    // Build the redirect URL with all required parameters.
    // The customer's browser is sent to Easypaisa's hosted checkout page.
    const params = new URLSearchParams({
      storeId,
      orderId,
      transactionAmount: amount,
      transactionType: "MA",           // MA = Merchant API
      paymentMethod: "WALLET",         // Default to wallet; user can change
      mobileNo: input.metadata?.mobileNo || "",
      emailAddress: input.metadata?.email || "",
      returnUrl,
      cancelUrl: input.cancelUrl,
      signature,
    });

    const checkoutUrl = `${EASYPAISA_API_HOST}${EASYPAISA_API_PATH}?${params.toString()}`;

    return {
      provider: "easypaisa",
      reference: orderId,
      redirectUrl: checkoutUrl,
      amount: input.amount,
      currency: "PKR",
      sandbox: !EASYPAISA_API_HOST.includes("easypay.easypaisa.com.pk"),
    };
  },

  /**
   * Server-side payment verification by order reference.
   *
   * In the hosted checkout flow, the primary verification happens through
   * the IPN callback (webhook). This method provides a fallback status check
   * by querying Easypaisa's order status API.
   */
  async verifyPayment(reference: string): Promise<PaymentVerificationResult> {
    // For the hosted checkout flow, the IPN webhook is the authoritative
    // verification path. This is a fallback that returns PENDING status,
    // indicating the webhook has not yet been received.
    return {
      provider: "easypaisa",
      status: "PENDING",
      amountPaise: null,
      currency: "PKR",
      transactionId: reference,
    };
  },
};
